// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ops/ops.proto

package ops

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployResult int32

const (
	DeployResult_DeployResultNone    DeployResult = 0
	DeployResult_DeployResultSuccess DeployResult = 1
	DeployResult_DeployResultFail    DeployResult = 2
)

var DeployResult_name = map[int32]string{
	0: "DeployResultNone",
	1: "DeployResultSuccess",
	2: "DeployResultFail",
}
var DeployResult_value = map[string]int32{
	"DeployResultNone":    0,
	"DeployResultSuccess": 1,
	"DeployResultFail":    2,
}

func (x DeployResult) String() string {
	return proto.EnumName(DeployResult_name, int32(x))
}
func (DeployResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ops_7c479f75a83dc4d1, []int{0}
}

type PingMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_7c479f75a83dc4d1, []int{0}
}
func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (dst *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(dst, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

type PongMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongMessage) Reset()         { *m = PongMessage{} }
func (m *PongMessage) String() string { return proto.CompactTextString(m) }
func (*PongMessage) ProtoMessage()    {}
func (*PongMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_7c479f75a83dc4d1, []int{1}
}
func (m *PongMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongMessage.Unmarshal(m, b)
}
func (m *PongMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongMessage.Marshal(b, m, deterministic)
}
func (dst *PongMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongMessage.Merge(dst, src)
}
func (m *PongMessage) XXX_Size() int {
	return xxx_messageInfo_PongMessage.Size(m)
}
func (m *PongMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PongMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PongMessage proto.InternalMessageInfo

type DeployRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	WorkloadID           string   `protobuf:"bytes,3,opt,name=WorkloadID,proto3" json:"WorkloadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_7c479f75a83dc4d1, []int{2}
}
func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (dst *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(dst, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *DeployRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployRequest) GetWorkloadID() string {
	if m != nil {
		return m.WorkloadID
	}
	return ""
}

type DeployResponse struct {
	Result               DeployResult `protobuf:"varint,1,opt,name=Result,proto3,enum=ops.DeployResult" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_7c479f75a83dc4d1, []int{3}
}
func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (dst *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(dst, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetResult() DeployResult {
	if m != nil {
		return m.Result
	}
	return DeployResult_DeployResultNone
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "ops.PingMessage")
	proto.RegisterType((*PongMessage)(nil), "ops.PongMessage")
	proto.RegisterType((*DeployRequest)(nil), "ops.DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "ops.DeployResponse")
	proto.RegisterEnum("ops.DeployResult", DeployResult_name, DeployResult_value)
}

func init() { proto.RegisterFile("ops/ops.proto", fileDescriptor_ops_7c479f75a83dc4d1) }

var fileDescriptor_ops_7c479f75a83dc4d1 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x93, 0x56, 0x22, 0x1d, 0x4d, 0x59, 0xa7, 0x82, 0xa1, 0x88, 0x48, 0x4e, 0x2a, 0x52,
	0xa1, 0x3d, 0x7a, 0x2d, 0x82, 0x07, 0x6b, 0x49, 0x0e, 0x9e, 0xd7, 0x38, 0x84, 0xda, 0x35, 0xb3,
	0x66, 0x12, 0xc1, 0x7f, 0x2f, 0xdd, 0xb6, 0x76, 0xdb, 0xe3, 0xfb, 0xe6, 0xb1, 0xf3, 0xe6, 0x2d,
	0xc4, 0x6c, 0xe5, 0x81, 0xad, 0x8c, 0x6c, 0xcd, 0x0d, 0x63, 0x97, 0xad, 0xa4, 0x31, 0x9c, 0xcc,
	0x17, 0x55, 0xf9, 0x42, 0x22, 0xba, 0x24, 0x27, 0x79, 0x27, 0x4b, 0x88, 0xa7, 0x64, 0x0d, 0xff,
	0x66, 0xf4, 0xdd, 0x92, 0x34, 0x98, 0xc0, 0xf1, 0xbc, 0xe6, 0x4f, 0x2a, 0x9a, 0x24, 0xbc, 0x0e,
	0x6f, 0x7a, 0xd9, 0x56, 0xe2, 0x25, 0xf4, 0x66, 0xfa, 0x8b, 0xc4, 0xea, 0x82, 0x92, 0x8e, 0x9b,
	0xed, 0x00, 0x5e, 0x01, 0xbc, 0x71, 0xbd, 0x34, 0xac, 0x3f, 0x9e, 0xa7, 0x49, 0xd7, 0x8d, 0x3d,
	0x92, 0x3e, 0x42, 0x7f, 0xbb, 0x48, 0x2c, 0x57, 0x42, 0x78, 0x0b, 0x51, 0x46, 0xd2, 0x9a, 0xf5,
	0xa2, 0xfe, 0xf8, 0x6c, 0xb4, 0x4a, 0xfe, 0x6f, 0x6a, 0x4d, 0x93, 0x6d, 0x0c, 0x77, 0x39, 0x9c,
	0xfa, 0x1c, 0xcf, 0x41, 0xf9, 0x7a, 0xc6, 0x15, 0xa9, 0x00, 0x2f, 0x60, 0xe0, 0xd3, 0xbc, 0x2d,
	0x0a, 0x12, 0x51, 0xe1, 0xa1, 0xfd, 0x49, 0x2f, 0x8c, 0xea, 0x8c, 0x97, 0x10, 0xbd, 0x5a, 0xc9,
	0xeb, 0x1f, 0xbc, 0x87, 0xa3, 0x55, 0x45, 0xa8, 0x5c, 0x02, 0xaf, 0xad, 0xe1, 0x86, 0x78, 0x85,
	0x05, 0x38, 0x81, 0x68, 0xfd, 0x1a, 0xe2, 0x5e, 0x62, 0xd7, 0xdf, 0x70, 0xb0, 0x7f, 0x85, 0x3b,
	0x35, 0x0d, 0xde, 0x23, 0xf7, 0x23, 0x93, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x2d, 0x87,
	0x7a, 0xa2, 0x01, 0x00, 0x00,
}
