// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ops/ops.proto

package ops

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployResult int32

const (
	DeployResult_DeployResultNone    DeployResult = 0
	DeployResult_DeployResultSuccess DeployResult = 1
	DeployResult_DeployResultFail    DeployResult = 2
)

var DeployResult_name = map[int32]string{
	0: "DeployResultNone",
	1: "DeployResultSuccess",
	2: "DeployResultFail",
}
var DeployResult_value = map[string]int32{
	"DeployResultNone":    0,
	"DeployResultSuccess": 1,
	"DeployResultFail":    2,
}

func (x DeployResult) String() string {
	return proto.EnumName(DeployResult_name, int32(x))
}
func (DeployResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ops_245907ece4d34e90, []int{0}
}

type PingMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_245907ece4d34e90, []int{0}
}
func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (dst *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(dst, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

type PongMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongMessage) Reset()         { *m = PongMessage{} }
func (m *PongMessage) String() string { return proto.CompactTextString(m) }
func (*PongMessage) ProtoMessage()    {}
func (*PongMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_245907ece4d34e90, []int{1}
}
func (m *PongMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongMessage.Unmarshal(m, b)
}
func (m *PongMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongMessage.Marshal(b, m, deterministic)
}
func (dst *PongMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongMessage.Merge(dst, src)
}
func (m *PongMessage) XXX_Size() int {
	return xxx_messageInfo_PongMessage.Size(m)
}
func (m *PongMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PongMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PongMessage proto.InternalMessageInfo

type DeployRequest struct {
	Project              string   `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	WorkloadID           string   `protobuf:"bytes,3,opt,name=WorkloadID,proto3" json:"WorkloadID,omitempty"`
	Metadata             string   `protobuf:"bytes,4,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_245907ece4d34e90, []int{2}
}
func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (dst *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(dst, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *DeployRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployRequest) GetWorkloadID() string {
	if m != nil {
		return m.WorkloadID
	}
	return ""
}

func (m *DeployRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *DeployRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeployResponse struct {
	Result               DeployResult `protobuf:"varint,1,opt,name=Result,proto3,enum=ops.DeployResult" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ops_245907ece4d34e90, []int{3}
}
func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (dst *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(dst, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetResult() DeployResult {
	if m != nil {
		return m.Result
	}
	return DeployResult_DeployResultNone
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "ops.PingMessage")
	proto.RegisterType((*PongMessage)(nil), "ops.PongMessage")
	proto.RegisterType((*DeployRequest)(nil), "ops.DeployRequest")
	proto.RegisterType((*DeployResponse)(nil), "ops.DeployResponse")
	proto.RegisterEnum("ops.DeployResult", DeployResult_name, DeployResult_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OpsSrvClient is the client API for OpsSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpsSrvClient interface {
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PongMessage, error)
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
}

type opsSrvClient struct {
	cc *grpc.ClientConn
}

func NewOpsSrvClient(cc *grpc.ClientConn) OpsSrvClient {
	return &opsSrvClient{cc}
}

func (c *opsSrvClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PongMessage, error) {
	out := new(PongMessage)
	err := c.cc.Invoke(ctx, "/ops.OpsSrv/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsSrvClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/ops.OpsSrv/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsSrvServer is the server API for OpsSrv service.
type OpsSrvServer interface {
	Ping(context.Context, *PingMessage) (*PongMessage, error)
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
}

func RegisterOpsSrvServer(s *grpc.Server, srv OpsSrvServer) {
	s.RegisterService(&_OpsSrv_serviceDesc, srv)
}

func _OpsSrv_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsSrvServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ops.OpsSrv/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsSrvServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsSrv_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsSrvServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ops.OpsSrv/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsSrvServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpsSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ops.OpsSrv",
	HandlerType: (*OpsSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OpsSrv_Ping_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _OpsSrv_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ops/ops.proto",
}

func init() { proto.RegisterFile("ops/ops.proto", fileDescriptor_ops_245907ece4d34e90) }

var fileDescriptor_ops_245907ece4d34e90 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdf, 0x4b, 0x3a, 0x41,
	0x14, 0xc5, 0x5d, 0x7f, 0xec, 0xf7, 0xeb, 0x2d, 0x65, 0xbb, 0x0a, 0x0d, 0x12, 0x11, 0x3e, 0x55,
	0x84, 0x81, 0x3e, 0xf6, 0x2a, 0x41, 0x0f, 0x9a, 0xac, 0x41, 0xcf, 0xd3, 0x7a, 0x11, 0x73, 0xdb,
	0x3b, 0xed, 0x9d, 0x0d, 0xfa, 0x53, 0xfa, 0x6f, 0xc3, 0x59, 0x7f, 0x8c, 0x3d, 0x7e, 0xce, 0xb9,
	0x0c, 0xe7, 0x9c, 0x81, 0x16, 0x1b, 0xb9, 0x67, 0x23, 0x03, 0x93, 0xb3, 0x65, 0xac, 0xb1, 0x91,
	0x7e, 0x0b, 0x4e, 0x66, 0xab, 0x6c, 0x39, 0x21, 0x11, 0xbd, 0x24, 0x87, 0x7c, 0xc0, 0x9f, 0x00,
	0x5a, 0x63, 0x32, 0x29, 0x7f, 0xc7, 0xf4, 0x59, 0x90, 0x58, 0x54, 0xf0, 0x6f, 0x96, 0xf3, 0x3b,
	0x25, 0x56, 0x05, 0x57, 0xc1, 0x75, 0x33, 0xde, 0x21, 0x5e, 0x40, 0x73, 0xaa, 0x3f, 0x48, 0x8c,
	0x4e, 0x48, 0x55, 0x9d, 0x77, 0x10, 0xf0, 0x12, 0xe0, 0x95, 0xf3, 0x75, 0xca, 0x7a, 0xf1, 0x34,
	0x56, 0x35, 0x67, 0x7b, 0x0a, 0xf6, 0xe0, 0xff, 0x84, 0xac, 0x5e, 0x68, 0xab, 0x55, 0xdd, 0xb9,
	0x7b, 0xc6, 0x2e, 0x34, 0x5e, 0x78, 0x4d, 0x99, 0x6a, 0x38, 0xa3, 0x84, 0xfe, 0x03, 0xb4, 0x77,
	0xd1, 0xc4, 0x70, 0x26, 0x84, 0x37, 0x10, 0xc6, 0x24, 0x45, 0x5a, 0x46, 0x6b, 0x0f, 0xcf, 0x06,
	0x9b, 0xb2, 0xfb, 0xa3, 0x22, 0xb5, 0xf1, 0xf6, 0xe0, 0x76, 0x0e, 0xa7, 0xbe, 0x8e, 0x5d, 0x88,
	0x7c, 0x9e, 0x72, 0x46, 0x51, 0x05, 0xcf, 0xa1, 0xe3, 0xab, 0xf3, 0x22, 0x49, 0x48, 0x24, 0x0a,
	0xfe, 0x9e, 0x3f, 0xea, 0x55, 0x1a, 0x55, 0x87, 0x6b, 0x08, 0x9f, 0x8d, 0xcc, 0xf3, 0x2f, 0xbc,
	0x83, 0xfa, 0x66, 0x55, 0x8c, 0x5c, 0x02, 0x6f, 0xe0, 0xde, 0x56, 0xf1, 0x36, 0xae, 0xe0, 0x08,
	0xc2, 0xf2, 0x35, 0xc4, 0xa3, 0xc4, 0x6e, 0xf1, 0x5e, 0xe7, 0xb8, 0x85, 0xab, 0xda, 0xaf, 0xbc,
	0x85, 0xee, 0x13, 0x47, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0x4f, 0x69, 0x14, 0xd5, 0x01,
	0x00, 0x00,
}
