// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ops

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OpsSrvClient is the client API for OpsSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpsSrvClient interface {
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PongMessage, error)
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
}

type opsSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsSrvClient(cc grpc.ClientConnInterface) OpsSrvClient {
	return &opsSrvClient{cc}
}

func (c *opsSrvClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PongMessage, error) {
	out := new(PongMessage)
	err := c.cc.Invoke(ctx, "/ops.OpsSrv/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *opsSrvClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/ops.OpsSrv/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsSrvServer is the server API for OpsSrv service.
// All implementations should embed UnimplementedOpsSrvServer
// for forward compatibility
type OpsSrvServer interface {
	Ping(context.Context, *PingMessage) (*PongMessage, error)
	Deploy(context.Context, *DeployRequest) (*DeployResponse, error)
}

// UnimplementedOpsSrvServer should be embedded to have forward compatible implementations.
type UnimplementedOpsSrvServer struct {
}

func (UnimplementedOpsSrvServer) Ping(context.Context, *PingMessage) (*PongMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOpsSrvServer) Deploy(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}

// UnsafeOpsSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsSrvServer will
// result in compilation errors.
type UnsafeOpsSrvServer interface {
	mustEmbedUnimplementedOpsSrvServer()
}

func RegisterOpsSrvServer(s grpc.ServiceRegistrar, srv OpsSrvServer) {
	s.RegisterService(&OpsSrv_ServiceDesc, srv)
}

func _OpsSrv_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsSrvServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ops.OpsSrv/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsSrvServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpsSrv_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsSrvServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ops.OpsSrv/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsSrvServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpsSrv_ServiceDesc is the grpc.ServiceDesc for OpsSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpsSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ops.OpsSrv",
	HandlerType: (*OpsSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OpsSrv_Ping_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _OpsSrv_Deploy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ops/ops.proto",
}
